### ISSUE TITLE
Uncaught TypeError: Failed to resolve module specifier "crypto"

### ISSUE THREAD

**Issue by causztic** [jamsocket/y-sweet#239]
Hi, I am exploring different providers for yjs and am evaluating y-sweet - facing this error message while creating the provider on the client side:

```
Uncaught TypeError: Failed to resolve module specifier "crypto". Relative references must start with either "/", "./", or "../".
```

I am able to get the clientToken correctly from `@y-sweet/sdk` on the server, but it seems that `@y-sweet/client` is importing node's crypto library, which doesn't play well for my project setup.

Since the only implementation (AFAIK) for `crypto` is to perform cache-busting, is it possible to use https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API instead? I can raise a PR for this

**Comment by paulgb** [comment]
Hi @causztic, thanks for reporting this. Since we don't need cryptographic randomness here, I think I'll just use math.random (which is supported in pretty much any JS-like environment) here and avoid the import entirely.

**Comment by paulgb** [comment]
Fix is merged, will do a version update + npm push shortly.

**Comment by causztic** [comment]
thank you for the quick update!
