### ISSUE TITLE
y-sweet image giving error while running docker container

### ISSUE THREAD

**Issue by ashukumar2001** [jamsocket/y-sweet#259]
![image](https://github.com/user-attachments/assets/89c5dbfd-95ec-4139-aee7-6cad571d00bc)

When i was running the image getting this error

**Comment by paulgb** [comment]
Hi @ashukumar2001, sorry for the slow reply, just saw this.

I believe what happened is that the version of y-sweet you had cached in Docker was not compatible with some changes we made recently to the Docker Compose file. I have tested with the latest to make sure it works now.

First, make sure you are on the latest image version:

```
docker pull ghcr.io/jamsocket/y-sweet:latest
docker run ghcr.io/jamsocket/y-sweet:latest y-sweet version
```

The second command should print 0.2.2.

Then, try passing `y-sweet serve`:

```
docker run -p 8080:8080 ghcr.io/jamsocket/y-sweet:latest y-sweet serve
```

Alternatively, you can run `npx y-sweet serve` if you have `npm` installed.
