### ISSUE TITLE
Local offline support

### ISSUE THREAD

**Issue by paulgb** [jamsocket/y-sweet#355]

**Comment by okatrppr** [comment]
It uses Yjs so right now https://github.com/yjs/y-indexeddb is the option, right?
I saw SurrealDB has wasm, https://github.com/surrealdb/surrealdb.wasm, can it be the other option?
Or are you planning to create new one?

**Comment by paulgb** [comment]
The plan is to create a new one. It's already actually mostly done (#354), just awaiting review internally.

The gist is that it uses indexeddb, but unlike `y-indexeddb`, it uses `WebCrypto` to encrypt the data locally.

**Comment by paulgb** [comment]
Closed by #354
